//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventurousContacts.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventurousContacts.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} ({2}).
        /// </summary>
        public static string ContactFormation {
            get {
                return ResourceManager.GetString("ContactFormation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Not Found.
        /// </summary>
        public static string ContactNotFound {
            get {
                return ResourceManager.GetString("ContactNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adventurous Contacts.
        /// </summary>
        public static string ContactTitle {
            get {
                return ResourceManager.GetString("ContactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASP NET MVC (1DV409).
        /// </summary>
        public static string Course {
            get {
                return ResourceManager.GetString("Course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create was unsuccessful. Please correct any errors and try again..
        /// </summary>
        public static string CreateFailedSummary {
            get {
                return ResourceManager.GetString("CreateFailedSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Contact.
        /// </summary>
        public static string CreateNewContact {
            get {
                return ResourceManager.GetString("CreateNewContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  was successfully created..
        /// </summary>
        public static string CreateSuccess {
            get {
                return ResourceManager.GetString("CreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you user you want to delete .
        /// </summary>
        public static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Contact.
        /// </summary>
        public static string DeleteContact {
            get {
                return ResourceManager.GetString("DeleteContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete was unsuccessful.
        /// </summary>
        public static string DeleteFailed {
            get {
                return ResourceManager.GetString("DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  was successfully deleted..
        /// </summary>
        public static string DeleteSuccess {
            get {
                return ResourceManager.GetString("DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry - but the contact you requested dosen&apos;t exist or was deleted..
        /// </summary>
        public static string DetailedContactNotFound {
            get {
                return ResourceManager.GetString("DetailedContactNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Contact.
        /// </summary>
        public static string EditContact {
            get {
                return ResourceManager.GetString("EditContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail address.
        /// </summary>
        public static string EmailName {
            get {
                return ResourceManager.GetString("EmailName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =================================================================================================================================================.
        /// </summary>
        public static string LogDivider {
            get {
                return ResourceManager.GetString("LogDivider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new contact.
        /// </summary>
        public static string NewContact {
            get {
                return ResourceManager.GetString("NewContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ooops! Server returned a 404 (page not found)! In English it means the page, address, url you are looking for has moved without leaving a forwarding address!.
        /// </summary>
        public static string PageNotFoundError {
            get {
                return ResourceManager.GetString("PageNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 404.
        /// </summary>
        public static string PageNotFoundTitle {
            get {
                return ResourceManager.GetString("PageNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laborationsuppgift 2.
        /// </summary>
        public static string Problem {
            get {
                return ResourceManager.GetString("Problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  was successfully saved..
        /// </summary>
        public static string SavedSuccess {
            get {
                return ResourceManager.GetString("SavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linnéuniversitetet.
        /// </summary>
        public static string School {
            get {
                return ResourceManager.GetString("School", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to contacts.
        /// </summary>
        public static string StartPageLink {
            get {
                return ResourceManager.GetString("StartPageLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steg 1.
        /// </summary>
        public static string Step {
            get {
                return ResourceManager.GetString("Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, an error occurred while processing your request..
        /// </summary>
        public static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
    }
}
